USE ht;
INSERT INTO `ht_namespaces` VALUES ('chi','University of Chicago','CHI','google');
INSERT INTO `ht_namespaces` VALUES ('coo','Cornell University','Cornell','google');
INSERT INTO `ht_namespaces` VALUES ('hvd','Harvard University','Harvard','google');
INSERT INTO `ht_namespaces` VALUES ('ien','Northwestern University','NWU','google');
INSERT INTO `ht_namespaces` VALUES ('inu','Indiana University','IND','google');
INSERT INTO `ht_namespaces` VALUES ('mdp','University of Michigan','UOM','google');
INSERT INTO `ht_namespaces` VALUES ('njp','Princeton University','PRNC','google');
INSERT INTO `ht_namespaces` VALUES ('nnc1','Columbia University','Columbia','google');
INSERT INTO `ht_namespaces` VALUES ('nyp','New York Public Library','NYPL','google');
INSERT INTO `ht_namespaces` VALUES ('pst','Penn State University','PSU','google');
INSERT INTO `ht_namespaces` VALUES ('pur1','Purdue University','PURD','google');
INSERT INTO `ht_namespaces` VALUES ('uc1','University of California','UCAL','google');
INSERT INTO `ht_namespaces` VALUES ('ucm','Universidad Complutense de Madrid','UCM','google');
INSERT INTO `ht_namespaces` VALUES ('uiug','University of Illinois','UIUC','google');
INSERT INTO `ht_namespaces` VALUES ('umn','University of Minnesota','MINN','google');
INSERT INTO `ht_namespaces` VALUES ('uva','University of Virginia','UVA','google');
INSERT INTO `ht_namespaces` VALUES ('wu','University of Wisconsin','Wisc','google');
INSERT INTO `ht_namespaces` VALUES ('bc','Boston College',NULL,'ia');
INSERT INTO `ht_namespaces` VALUES ('dul1','Duke University',NULL,'ia');
INSERT INTO `ht_namespaces` VALUES ('gri','Getty Research Institute',NULL,'ia');
INSERT INTO `ht_namespaces` VALUES ('loc','Library of Congress',NULL,'ia');
INSERT INTO `ht_namespaces` VALUES ('nc01','University of North Carolina at Chapel Hill',NULL,'ia');
INSERT INTO `ht_namespaces` VALUES ('ncs1','North Carolina State University',NULL,'ia');
INSERT INTO `ht_namespaces` VALUES ('nnc2','Columbia University',NULL,'ia');
INSERT INTO `ht_namespaces` VALUES ('psia','Penn State University',NULL,'ia');
INSERT INTO `ht_namespaces` VALUES ('pur2','Purdue University',NULL,'ia');
INSERT INTO `ht_namespaces` VALUES ('uc2','University of California',NULL,'ia');
INSERT INTO `ht_namespaces` VALUES ('uiuo','University of Illinois',NULL,'ia');
INSERT INTO `ht_namespaces` VALUES ('miua','University of Michigan',NULL,'lit-dlps-dc');
INSERT INTO `ht_namespaces` VALUES ('miun','University of Michigan',NULL,'lit-dlps-dc');
INSERT INTO `ht_namespaces` VALUES ('mdl','Minnesota Digital Library',NULL,'mhs');
INSERT INTO `ht_namespaces` VALUES ('usu','Utah State University Press',NULL,'usup');
INSERT INTO `ht_namespaces` VALUES ('yale','Yale University',NULL,'yale');
INSERT INTO `ht_namespaces` VALUES ('ufl1','University of Florida',NULL,'ia');
INSERT INTO `ht_namespaces` VALUES ('keio','Keio University','Keio','google');
INSERT INTO `ht_namespaces` VALUES ('osu','The Ohio State University','OSU','google');
INSERT INTO `ht_namespaces` VALUES ('txa','Texas A&amp;M University',NULL,'txa');
INSERT INTO `ht_namespaces` VALUES ('uma','University of Massachusetts Amherst',NULL,'ia');
INSERT INTO `ht_namespaces` VALUES ('ufl2','University of Florida',NULL,'uf');
INSERT INTO `ht_namespaces` VALUES ('udel','University of Delaware',NULL,'udel');
INSERT INTO `ht_namespaces` VALUES ('aeu','University of Alberta',NULL,'ia');
INSERT INTO `ht_namespaces` VALUES ('ucw','University of Connecticut',NULL,'ia');
INSERT INTO `ht_namespaces` VALUES ('caia','Clark Art Institute',NULL,'ia');
INSERT INTO `ht_namespaces` VALUES ('uiuc','University of Illinois - Urbana Champaign',NULL,'uiuc');
INSERT INTO `ht_namespaces` VALUES ('ku01','Knowledge Unlatched',NULL,'ku');
INSERT INTO `ht_namespaces` VALUES ('mcg','McGill University',NULL,'mcgill');
INSERT INTO `ht_namespaces` VALUES ('msu','Michigan State University','MSU','google');
INSERT INTO `ht_namespaces` VALUES ('yul','Yale University',NULL,'yale2');
INSERT INTO `ht_namespaces` VALUES ('mou','University of Missouri',NULL,'mou');
INSERT INTO `ht_namespaces` VALUES ('wau','University of Washington',NULL,'chtanc');
INSERT INTO `ht_namespaces` VALUES ('emu','Emory University',NULL,'geu');
INSERT INTO `ht_namespaces` VALUES ('iau','University of Iowa','IOWA','google');
INSERT INTO `ht_namespaces` VALUES ('mmet','Tufts University',NULL,'ia');
INSERT INTO `ht_namespaces` VALUES ('umd','University of Maryland',NULL,'umd');
INSERT INTO `ht_namespaces` VALUES ('frick','The Frick Collection',NULL,'frick');
INSERT INTO `ht_namespaces` VALUES ('ia','Internet Archive',NULL,'ia');
INSERT INTO `ht_namespaces` VALUES ('txu','University of Texas','UTEXAS','google');
INSERT INTO `ht_namespaces` VALUES ('uiul','University of Illinois Law','UIUL','google');
